"""
Report service — orchestrates:
AI Report → HTML templates → PDF → Email → DB record
"""
import json
from datetime import datetime
from typing import Optional, List
from sqlalchemy.orm import Session

from app.db.models.machine import Machine
from app.db.models.report import Report
from app.db.models.user import User
from app.db.models.engineer_machine_assignment import EngineerMachineAssignment
from app.ai.report_generator import generate_report
from app.services.pdf_service import generate_engineer_report_pdf, generate_admin_report_pdf
from app.services.email_service import send_alert_email_engineer, send_alert_email_admin
from app.core.logging import logger


def _build_template_context(machine: Machine, ai_result, trigger_event: str) -> dict:
    """Build context dict for both HTML templates."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return {
        "machine": {
            "code": machine.machine_code,
            "name": machine.name,
            "location": machine.location or "—",
            "type": machine.machine_type or "—",
            "status": machine.status,
            "health_score": machine.health_score,
            "rpm": machine.rpm,
            "temperature": machine.temperature,
            "vibration_rms": machine.vibration_rms,
            "kurtosis": machine.kurtosis,
            "crest_factor": machine.crest_factor,
        },
        "ai": ai_result.to_dict(),
        "trigger_event": trigger_event,
        "generated_at": now,
    }


def trigger_report_pipeline(
    db: Session,
    machine: Machine,
    trigger_event: str = "Manual",
    alert_id: Optional[int] = None,
    maintenance_id: Optional[int] = None,
    generated_by: Optional[int] = None,
    send_emails: bool = True,
) -> List[Report]:
    """
    Full report pipeline:
    1. AI report generation
    2. HTML context build
    3. Engineer PDF + Admin PDF
    4. DB record creation
    5. Email dispatch
    Returns list of created Report records.
    """
    reports = []

    # 1. AI report
    ai_result = generate_report(db, machine, trigger_event)
    ai_json = json.dumps(ai_result.to_dict())
    context = _build_template_context(machine, ai_result, trigger_event)

    # 2. Generate engineer PDF
    eng_pdf = generate_engineer_report_pdf(context)
    eng_report = Report(
        machine_id=machine.id,
        alert_id=alert_id,
        maintenance_id=maintenance_id,
        report_type="ENGINEER",
        trigger_event=trigger_event,
        ai_result=ai_json,
        pdf_path=eng_pdf,
        generated_by=generated_by,
    )
    db.add(eng_report)

    # 3. Generate admin PDF
    admin_pdf = generate_admin_report_pdf(context)
    admin_report = Report(
        machine_id=machine.id,
        alert_id=alert_id,
        maintenance_id=maintenance_id,
        report_type="ADMIN",
        trigger_event=trigger_event,
        ai_result=ai_json,
        pdf_path=admin_pdf,
        generated_by=generated_by,
    )
    db.add(admin_report)
    db.commit()
    db.refresh(eng_report)
    db.refresh(admin_report)
    reports.extend([eng_report, admin_report])

    # 4. Email dispatch
    if send_emails:
        _dispatch_emails(db, machine, eng_pdf, admin_pdf, generated_by)

    logger.info(f"Report pipeline complete for {machine.machine_code}")
    return reports


def _dispatch_emails(
    db: Session,
    machine: Machine,
    eng_pdf: Optional[str],
    admin_pdf: Optional[str],
    generated_by: Optional[int] = None,
) -> None:
    """
    Send role-specific PDF report emails:
    - If generated by ADMIN -> Alert Engineer (send Technical Engineer PDF report to assigned engineers)
    - If generated by ENGINEER -> Alert Factory/Admin (send Operational Admin PDF report to plant admins)
    - If system/automated -> send both to respective parties.
    """
    generator_user = db.query(User).filter(User.id == generated_by).first() if generated_by else None
    sender_role = generator_user.role if generator_user else None

    # Find assigned engineers for this machine
    assignments = (
        db.query(EngineerMachineAssignment)
        .filter(
            EngineerMachineAssignment.machine_id == machine.id,
            EngineerMachineAssignment.is_active == True,
        )
        .all()
    )
    engineer_ids = [a.engineer_id for a in assignments]
    engineers = db.query(User).filter(User.id.in_(engineer_ids)).all() if engineer_ids else []

    # Fallback to all active engineers if none assigned specifically
    if not engineers:
        engineers = db.query(User).filter(User.role == "ENGINEER", User.is_active == True).all()

    # Find all admins
    admins = db.query(User).filter(User.role == "ADMIN", User.is_active == True).all()

    # 1. Admin alerting Engineer -> Email Engineer PDF report to Engineers
    if sender_role == "ADMIN" or sender_role is None:
        for eng in engineers:
            logger.info(f"Sending Technical Engineer Report PDF to assigned engineer {eng.email}")
            send_alert_email_engineer(eng.email, machine.machine_code, eng_pdf or "")

    # 2. Engineer alerting Factory/Admin -> Email Admin PDF report to Admins
    if sender_role == "ENGINEER" or sender_role is None:
        for adm in admins:
            logger.info(f"Sending Operational Admin Report PDF to factory admin {adm.email}")
            send_alert_email_admin(adm.email, machine.machine_code, admin_pdf or "")

